resume_from_checkpoint_path: null
result_path: "result"
model_path: null
dataset_paths: /home/trung/Documents/generate data/CROHME2023_256x512
tokenizer: "dataset/tokenizer.json"
exp_name: "nougat"
train_batch_sizes: 2
num_workers: 8
val_batch_sizes: 2
#val_batches: 1
# swin transformer
input_size: [256, 256]
align_long_axis: False
encoder_layer: [2, 2, 14, 2]
window_size: 7
patch_size: 4
embed_dim: 128
num_heads: [4, 8, 16, 32]

# BART
max_length: 512
max_position_embeddings: 512
hidden_dimension: 768
decoder_layer: 2

accumulate_grad_batches: 1
num_nodes: 1
seed: 25
lr: 5e-5
min_lr: 7.5e-6
lr_step: 16
gamma: 0.9996
warmup_steps: 250
num_training_samples_per_epoch: 10000
max_epochs: 30
max_steps: -1
val_check_interval: null
check_val_every_n_epoch: 1
gradient_clip_val: 0.5
verbose: False
